version: '3'

services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DATABASE=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./backend/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - postgres-data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - postgres

  frontend:
    build:
      context: .
      dockerfile: frontend/threaddit/Dockerfile
    container_name: frontend
    ports:
      - "80:80"
      - "3000:3000"
    restart: always
    environment:
      - REACT_APP_API_URL=http://backend:5000/api
    depends_on:
      - backend
volumes:
  postgres-data:
