version: '3'

services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_USER=postgres
      - POSTGRES_DATABASE=myapp
    ports:
      - "5432:5432"
    volumes:
      - ./backend/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - postgres-data:/var/lib/postgresql/data
  app:
    image: threaddit:latest
    restart: always
    ports:
      - "8080:5000"
    depends_on:
      - postgres  
volumes:
  postgres-data:
