services:
  postgres:
    image: postgres:13
    restart: always
    container_name: threaddit_db
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - ./backend/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - postgres-data:/var/lib/postgresql/data
    networks:
      - threaddit-network

  app:
    image: thdyu/threaddit:latest
    container_name: threaddit_app
    restart: always
    environment:
      - DATABASE_URI=${DATABASE_URI}
      - SECRET_KEY=${SECRET_KEY}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
    ports:
      - "8888:5000"
    depends_on:
      - postgres
    networks:
      - threaddit-network

volumes:
  postgres-data:

networks:
  threaddit-network:
    driver: bridge
