apiVersion: v1
kind: Service
metadata:
  namespace: threaddit
  labels:
    app: threaddit
  name: threaddit
spec:
  ports:
    - name: "5000"
      port: 5000
      targetPort: 5000
  selector:
    app: threaddit
