apiVersion: v1
kind: Service
metadata:
  namespace: threaddit
  labels:
    app: threaddit
  name: threaddit
spec:
  type: LoadBalancer
  ports:
    - name: "80"
      port: 80
      targetPort: 5000
      protocol: TCP
      name: http
  selector:
    app: threaddit
