apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: threaddit
  labels:
    app: threaddit
  name: threaddit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: threaddit
  template:
    metadata:
      labels:
        app: threaddit
    spec:
      containers:
        - name: threaddit-app
          image: callmenaul/threaddit-v75:latest
          envFrom:
            - secretRef:
                name: threaddit-secret
          ports:
            - containerPort: 5000
              protocol: TCP
      restartPolicy: Always
