apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: threaddit
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      service: nginx
  template:
    metadata:
      labels:
        service: nginx
    spec:
      containers:
        - image: nginx:latest
          name: nginx
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/nginx/conf.d/default.conf
              name: nginx-cm0
              subPath: default.conf
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: default.conf
                path: default.conf
            name: nginx-cm0
          name: nginx-cm0
