apiVersion: v1
kind: ConfigMap
metadata:
  namespace: threaddit
  labels:
    service: nginx
  name: nginx-cm0
data:
#  default.conf: "upstream threaddit {\n    server threaddit:5000;\n}\n\nserver {\n    listen 80;\n    location / {\n        proxy_set_header Host $host;\n        proxy_set_header X-Real-IP $remote_addr;\n        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n        proxy_set_header X-Forwarded-Proto $scheme;\n\n        proxy_http_version 1.1;\n        proxy_set_header Upgrade $http_upgrade;\n        proxy_set_header Connection \"upgrade\";\n        proxy_pass http://threaddit/;\n    }\n}"
  default.conf: |
    upstream threaddit {
        server threaddit:5000;
    }

    server {
        listen 80;

        proxy_buffering on;

        proxy_read_timeout 60s;

        location / {
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_pass http://threaddit;
        }
    }
