apiVersion: v1
kind: Service
metadata:
  namespace: threaddit
  labels:
    app: postgres
  name: postgres
spec:
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
  selector:
    app: postgres
