apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: threaddit
  labels:
    app: postgres-data
  name: postgres-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn
